loadstring(game:HttpGet("https://raw.githubusercontent.com/avrcal/r15/refs/heads/main/Tools.luau",true))()

_G.tools = {
    {name = "spin", Id = 87093097413514},
    {name = "johncena", Id = 132069223994128},
    {name = "hide", Id = 126193377347657},
    {name = "Danganronpa Monokuma Dance", Id = 136288334711651},
    {name = "Flying Bird", Id = 126285359578816},
    {name = "Golden Freddy Pose", Id = 138402679058341},
    {name = "Charleston", Id = 72556581432614},
    {name = "Obby", Id = 71337558824888},
    {name = "Wiggly Worm", Id = 83400387781374},
    {name = "Tank Transformation", Id = 94915612757079}







}
